// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: nflog/nflogpb/nflog.proto

package nflogpb

import (
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Receiver struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configured name of the receiver group.
	GroupName string `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	// Name of the integration of the receiver.
	Integration string `protobuf:"bytes,2,opt,name=integration,proto3" json:"integration,omitempty"`
	// Index of the receiver with respect to the integration.
	// Every integration in a group may have 0..N configurations.
	Idx           uint32 `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receiver) Reset() {
	*x = Receiver{}
	mi := &file_nflog_nflogpb_nflog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receiver) ProtoMessage() {}

func (x *Receiver) ProtoReflect() protoreflect.Message {
	mi := &file_nflog_nflogpb_nflog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receiver.ProtoReflect.Descriptor instead.
func (*Receiver) Descriptor() ([]byte, []int) {
	return file_nflog_nflogpb_nflog_proto_rawDescGZIP(), []int{0}
}

func (x *Receiver) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Receiver) GetIntegration() string {
	if x != nil {
		return x.Integration
	}
	return ""
}

func (x *Receiver) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

// Entry holds information about a successful notification
// sent to a receiver.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key identifying the dispatching group.
	GroupKey []byte `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	// The receiver that was notified.
	Receiver *Receiver `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// Timestamp of the succeeding notification.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// FiringAlerts list of hashes of firing alerts at the last notification time.
	FiringAlerts []uint64 `protobuf:"varint,6,rep,packed,name=firing_alerts,json=firingAlerts,proto3" json:"firing_alerts,omitempty"`
	// ResolvedAlerts list of hashes of resolved alerts at the last notification time.
	ResolvedAlerts []uint64 `protobuf:"varint,7,rep,packed,name=resolved_alerts,json=resolvedAlerts,proto3" json:"resolved_alerts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_nflog_nflogpb_nflog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_nflog_nflogpb_nflog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_nflog_nflogpb_nflog_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetGroupKey() []byte {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

func (x *Entry) GetReceiver() *Receiver {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *Entry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Entry) GetFiringAlerts() []uint64 {
	if x != nil {
		return x.FiringAlerts
	}
	return nil
}

func (x *Entry) GetResolvedAlerts() []uint64 {
	if x != nil {
		return x.ResolvedAlerts
	}
	return nil
}

// MeshEntry is a wrapper message to communicate a notify log
// entry through a mesh network.
type MeshEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The original raw notify log entry.
	Entry *Entry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	// A timestamp indicating when the mesh peer should evict
	// the log entry from its state.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshEntry) Reset() {
	*x = MeshEntry{}
	mi := &file_nflog_nflogpb_nflog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshEntry) ProtoMessage() {}

func (x *MeshEntry) ProtoReflect() protoreflect.Message {
	mi := &file_nflog_nflogpb_nflog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshEntry.ProtoReflect.Descriptor instead.
func (*MeshEntry) Descriptor() ([]byte, []int) {
	return file_nflog_nflogpb_nflog_proto_rawDescGZIP(), []int{2}
}

func (x *MeshEntry) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *MeshEntry) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_nflog_nflogpb_nflog_proto protoreflect.FileDescriptor

const file_nflog_nflogpb_nflog_proto_rawDesc = "" +
	"\n" +
	"\x19nflog/nflogpb/nflog.proto\x12\anflogpb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14gogoproto/gogo.proto\"]\n" +
	"\bReceiver\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12 \n" +
	"\vintegration\x18\x02 \x01(\tR\vintegration\x12\x10\n" +
	"\x03idx\x18\x03 \x01(\rR\x03idx\"\xe5\x01\n" +
	"\x05Entry\x12\x1b\n" +
	"\tgroup_key\x18\x01 \x01(\fR\bgroupKey\x12-\n" +
	"\breceiver\x18\x02 \x01(\v2\x11.nflogpb.ReceiverR\breceiver\x12B\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\ttimestamp\x12#\n" +
	"\rfiring_alerts\x18\x06 \x03(\x04R\ffiringAlerts\x12'\n" +
	"\x0fresolved_alerts\x18\a \x03(\x04R\x0eresolvedAlerts\"v\n" +
	"\tMeshEntry\x12$\n" +
	"\x05entry\x18\x01 \x01(\v2\x0e.nflogpb.EntryR\x05entry\x12C\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\b\xc8\xde\x1f\x00\x90\xdf\x1f\x01R\texpiresAtB!\xc8\xe1\x1e\x00\xc8\xe2\x1e\x01\xd0\xe2\x1e\x01\xe0\xe2\x1e\x01Z\x0f./nflog/nflogpbb\x06proto3"

var (
	file_nflog_nflogpb_nflog_proto_rawDescOnce sync.Once
	file_nflog_nflogpb_nflog_proto_rawDescData []byte
)

func file_nflog_nflogpb_nflog_proto_rawDescGZIP() []byte {
	file_nflog_nflogpb_nflog_proto_rawDescOnce.Do(func() {
		file_nflog_nflogpb_nflog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nflog_nflogpb_nflog_proto_rawDesc), len(file_nflog_nflogpb_nflog_proto_rawDesc)))
	})
	return file_nflog_nflogpb_nflog_proto_rawDescData
}

var file_nflog_nflogpb_nflog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nflog_nflogpb_nflog_proto_goTypes = []any{
	(*Receiver)(nil),              // 0: nflogpb.Receiver
	(*Entry)(nil),                 // 1: nflogpb.Entry
	(*MeshEntry)(nil),             // 2: nflogpb.MeshEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_nflog_nflogpb_nflog_proto_depIdxs = []int32{
	0, // 0: nflogpb.Entry.receiver:type_name -> nflogpb.Receiver
	3, // 1: nflogpb.Entry.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: nflogpb.MeshEntry.entry:type_name -> nflogpb.Entry
	3, // 3: nflogpb.MeshEntry.expires_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nflog_nflogpb_nflog_proto_init() }
func file_nflog_nflogpb_nflog_proto_init() {
	if File_nflog_nflogpb_nflog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nflog_nflogpb_nflog_proto_rawDesc), len(file_nflog_nflogpb_nflog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nflog_nflogpb_nflog_proto_goTypes,
		DependencyIndexes: file_nflog_nflogpb_nflog_proto_depIdxs,
		MessageInfos:      file_nflog_nflogpb_nflog_proto_msgTypes,
	}.Build()
	File_nflog_nflogpb_nflog_proto = out.File
	file_nflog_nflogpb_nflog_proto_goTypes = nil
	file_nflog_nflogpb_nflog_proto_depIdxs = nil
}
