FROM debian:bookworm-slim

WORKDIR /app

COPY bin/prometheus /bin/prometheus
COPY assets/prometheus.yaml /etc/prometheus/prometheus.yaml

EXPOSE 9090
ENTRYPOINT [ "/bin/prometheus" ]
CMD        [ "--config.file=/etc/prometheus/prometheus.yaml" ]
