FROM debian:bookworm-slim

WORKDIR /app

COPY bin/alertmanager /bin/alertmanager
COPY assets/alertmanager.yaml /etc/alertmanager/alertmanager.yaml

EXPOSE 9093
ENTRYPOINT [ "/bin/alertmanager" ]
CMD        [ "--config.file=/etc/alertmanager/alertmanager.yaml" ]
